# Generated by Django 5.2 on 2025-04-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='status',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nome',
            field=models.CharField(default='Cliente Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(default='Cliente Desconhecido', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='servico',
            field=models.CharField(choices=[('Corte de Cabelo', 'Corte de Cabelo'), ('Barba', 'Barba'), ('Corte + Barba', 'Corte + Barba'), ('Sobrancelha', 'Sobrancelha')], max_length=50),
        ),
    ]
