# Generated by Django 5.2 on 2025-04-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_remove_agendamento_cliente_remove_agendamento_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
